name: OmmaTeam Back-End CI pipeline for microservices

on:
  push:
    paths:
      - 'services/**'
      - '.github/**'
      - 'shared/**'
  pull_request:
    paths:
      - 'services/**'
      - 'shared/**'

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      team: ${{ steps.filter.outputs.team }}
      register: ${{ steps.filter.outputs.register }}

    steps:
      - uses: actions/checkout@v3
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            team:
              - 'services/team-service/**'
              - 'shared/**'
            register:
              - 'services/register-service/**'
              - 'shared/**'

  team-service:
    name: Run tests for register-service
    needs: check-paths
    if: needs.check-paths.outputs.team == 'true'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: services/team-service
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check omma-shared-lib package version
        run: |
          local_version=$(npm list omma-shared-lib --json | jq -r '.dependencies["omma-shared-lib"].version' || echo "not_installed")
          latest_version=$(npm view omma-shared-lib version)
          echo "Local version: $local_version"
          echo "Latest version: $latest_version"
          if [ "$local_version" = "not_installed" ]; then
            echo "::warning::omma-shared-lib is not installed locally."
          elif [ "$local_version" != "$latest_version" ]; then
            echo "::warning::New version of omma-shared-lib available! Local: $local_version, Latest: $latest_version"
            exit 1
          else
            echo "omma-shared-lib is up-to-date."
          fi
        shell: bash

  register-service:
    name: Run tests for register-service
    needs: check-paths
    if: needs.check-paths.outputs.register == 'true'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: omma_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: services/register-service

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 1
          done
      - name: Installing dependencies
        run: npm install

      - name: Generate Prisma client
        run: npx prisma generate --schema=./node_modules/omma-shared-lib/prisma/schema.prisma

      - name: Apply Prisma migrations
        run: npx prisma migrate deploy --schema=./node_modules/omma-shared-lib/prisma/schema.prisma
        env:
          DATABASE_URL: postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/omma_db?schema=public

      - name: Building the app
        run: npm run build

      - name: Check omma-shared-lib package version
        run: |
          local_version=$(npm list omma-shared-lib --json | jq -r '.dependencies["omma-shared-lib"].version' || echo "not_installed")
          latest_version=$(npm view omma-shared-lib version)
          echo "Local version: $local_version"
          echo "Latest version: $latest_version"
          if [ "$local_version" = "not_installed" ]; then
            echo "::warning::omma-shared-lib is not installed locally."
          elif [ "$local_version" != "$latest_version" ]; then
            echo "::warning::New version of omma-shared-lib available! Local: $local_version, Latest: $latest_version"
            exit 1
          else
            echo "omma-shared-lib is up-to-date."
          fi
        shell: bash


      - name: Running  E2E tests
        run: npm run test:e2e
